openapi: 3.0.1
info:
  title: Minimal project with connexion
  description: Sample project
  version: 1.0.0
servers:
  - url: /api/v1/test
paths:
  /entry:
    post:
      operationId: sample_code.endpoints.endpoint.post
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                kind:
                  type: string
                  description: 'Request current time or date'
                  enum:
                    - time
                    - date
              required:
                - kind
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  theResponse:
                    type: string

